- name: Crear grupo GProfesores
  become: yes
  group:
    name: GProfesores
    state: present
    

- name: Crear grupo GAlumnos
  become: yes
  group:
    name: GAlumnos
    state: present
    

- name: Crear usuario Profesor y agregar a GProfesores
  become: yes
  user:
    name: Profesor
    groups: GProfesores
    append: yes
    state: present
    create_home: yes
    

- name: Crear usuario alumno y agregar a GAlumnos
  become: yes
  user:
    name: alumno
    groups: GAlumnos
    append: yes
    state: present
    create_home: yes
    
