- name: Ejecutar tareas sin privilegios
  hosts: servidor
  roles:
    - 2do_parcial

- name: Ejecutar tareas con privilegios root
  hosts: servidor
  become: yes
  roles:
    - Alta_Usuarios_belsito
    - Sudoers_belsito
    - Instala_tools_belsito

