
- hosts: all

  tasks:
    - include_role:
        name: 2do_parcial
    - include_role:
        name: Alta_Usuarios_belsito
    - include_role:
        name: Sudoers_belsito
    - include_role:
        name: Instala_tools_belsito
    
    - name: "Otra tarea"
      debug:
        msg: "Me estoy ejecutando despues de los Roles"
